spring:
  datasource:
    url: jdbc:mariadb:// 127.0.0.1:3306/library
    hikari:
      username: admin
      password: changeme
  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false

